name: CI - Publish new versions

on:
  push:
    branches:
      - master

jobs:
  publish_release:
    name: Publish new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Slack Notification
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_PRODUCT_WEBHOOK }}
          SLACK_USERNAME: Messenger Bot
          SLACK_ICON_EMOJI: ":colis:"
          SLACK_COLOR: "#CF7F5F"
          SLACK_TITLE: New version published !
          MSG_MINIMAL: true
